import moment from "moment";
import { getPosts } from "../../src/helpers/PostsDatabase";
import styles from "./Posts.module.scss";
import { PostCategory } from "../../src/types";
import { CloudDev, IoTDev, WebDev } from "../../src/icons";
import { Montserrat, Poppins } from "@next/font/google";

const poppins = Poppins({
    weight: ["400", "500", "600", "700", "800", "900"],
    variable: "--poppins-font",
    subsets: ["latin"],
});

const montserrat = Montserrat({
    weight: ["400", "500", "600", "700", "800", "900"],
    variable: "--montserrat-normal",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const getIcon = (category: PostCategory): React.ReactNode => {
    switch (category) {
        case "IOT_DEV":
            return <IoTDev />;
        case "WEB_DEV":
            return <WebDev />;
        case "CLOUD_DEV":
            return <CloudDev />;
    }
};

async function GetPosts() {
    const posts = await getPosts();
    return (
        <div className={styles.postsList}>
            <ul>
                {posts
                    ?.filter((post) => !post.isDraft)
                    .map((post, index) => (
                        <li className={styles.postItem} key={index}>
                            {getIcon(post.type)}
                            <div>
                                <p>{post.title}</p>
                                <p>{moment(post.date).format("M/DD/YYYY")}</p>
                            </div>
                        </li>
                    ))}
            </ul>
        </div>
    );
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <div className={styles.postsLayout}>
            {/* @ts-ignore */}
            <GetPosts />
            {children}
        </div>
    );
}
