import moment from "moment";

import styles from "./Posts.module.scss";
import { PostCategory } from "../../types";
import { CloudDev, IoTDev, WebDev } from "../../client/icons";
import { Montserrat, Poppins } from "next/font/google";
import { getPosts } from "../../server/helpers/PostsDatabase";
import { Suspense } from "react";
import Loading from "./loading";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

function timeout(ms: number) {
    return new Promise((resolve) => setTimeout(resolve, ms));
}

const getIcon = (category: PostCategory): React.ReactNode => {
    switch (category) {
        case "IOT_DEV":
            return <IoTDev />;
        case "WEB_DEV":
            return <WebDev />;
        case "CLOUD_DEV":
            return <CloudDev />;
    }
};

async function GetPosts() {
    await timeout(4000);
    const posts = await getPosts();
    return (
        <div className={styles.postsList}>
            <ul>
                {posts
                    ?.filter((post) => !post.isDraft)
                    .map((post, index) => (
                        <li className={styles.postItem} key={index}>
                            {getIcon(post.type)}
                            <div>
                                <p>{post.title}</p>
                                <p>{moment(post.date).format("M/DD/YYYY")}</p>
                            </div>
                        </li>
                    ))}
            </ul>
        </div>
    );
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <Suspense fallback={<Loading />}>
            <div className={styles.postsLayout}>
                {/* @ts-ignore */}
                <GetPosts />

                {children}
            </div>
        </Suspense>
    );
}
