import "./globals.scss";
import { Header } from "../src/components";
import UIThemeContextProvider from "../src/providers/UIThemeContextProvider";
import styles from "./page.module.scss";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html
            lang="en"
            style={{ display: "flex", flexDirection: "column-reverse" }}
        >
            <UIThemeContextProvider>
                <header className={styles.header}>
                    <Header />
                </header>
                <body style={{ position: "relative" }}>{children}</body>
            </UIThemeContextProvider>
        </html>
    );
}
