import "./globals.scss";
import Header from "./Header/Header";
import UIThemeContextProvider from "../client/providers/UIThemeContextProvider";
import { Poppins, Montserrat } from "next/font/google";
import AuthContextProvider from "../client/providers/AuthContextProvider";

const poppins = Poppins({
    weight: ["400", "500", "600", "700", "800", "900"],
    variable: "--poppins-font",
    subsets: ["latin"],
    display: "swap",
});

const montserrat = Montserrat({
    weight: ["400", "500", "600", "700", "800", "900"],
    variable: "--montserrat",
    subsets: ["latin"],
    display: "swap",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html
            lang="en"
            style={{ display: "flex", flexDirection: "column-reverse" }}
            className={`${poppins.className} ${montserrat.className}`}
        >
            <AuthContextProvider>
                <UIThemeContextProvider>
                    <header>
                        <Header />
                    </header>
                    <body style={{ position: "relative" }}>{children}</body>
                </UIThemeContextProvider>
            </AuthContextProvider>
        </html>
    );
}
